config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/home/profile', to: 'home#profile'
  devise_for :admins, path: 'admins'
  devise_for :clients, path: 'clients'
  get '/clients/delete', to: 'clients#delete'
  post '/clients/delete', to: 'clients#delete'
  get '/clients/changeaccount', to: 'clients#changeaccount'
  post '/clients/changeaccount', to: 'clients#changeaccount'
  get 'search', to: 'admin/clients#search'

  resources :messages, only: %i[create]

  resources :orders, only: %I[index show] do
    post 'cancel', on: :member
    post 'pay', on: :member
  end

  resources :service_desks do
    post 'change_to_wait_approval_client', on: :member
    post 'close', on: :member
  end

  resources :credit_cards, only: %I[index new create] do
    post :down, :up, on: :member
  end

  resources :products, only: %I[index show] do
    post 'cancel', on: :member
    get 'buy', on: :member
    get 'choose_period', on: :member
    post 'create_order', on: :member
  end

  namespace :admin do
    resources :categories, only: %i[index new create edit update destroy]
    resources :clients, only: %I[index show]
    resources :products, only: %I[index show] do
      post 'cancel', on: :member
    end
    resources :orders, only: %I[index show] do
      post 'cancel', on: :member
    end
    resources :service_desks, only: %I[index show] do
      post 'close', on: :member
    end

    get 'my_service_desks', to: 'service_desks#my_service_desks'
    post 'assign_service_desk/:id', to: 'service_desks#assign_service_desk', as: :assign_service_desk
    resources :messages, only: %i[create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :orders, only: :show do
        patch 'payment', on: :collection
      end
      patch 'cancelation/:id', to: 'orders#cancelation', as: 'cancelation'
      get 'card_banners/:token', to: 'banners#show'
    end
  end
end

app/models/service_desk.rb
class ServiceDesk < ApplicationRecord
  belongs_to :category
  belongs_to :client
  belongs_to :admin, optional: true
  belongs_to :order, optional: true
  has_many :messages, dependent: :nullify
  validates :description, presence: true

  enum status: { open: 0, in_progress: 1, wait_approval_client: 2, closed: 3 }

  STATUS = [
    ['Status', nil],
    ['Aberto', 0],
    ['Em Andamento', 1],
    ['Aguardando Resposta do Cliente', 2],
    ['Fechado', 3]
  ].freeze

  def self.status
    STATUS
  end

  def created
    created_at.strftime('%d/%m/%Y')
  end

  def closed
    updated_at.strftime('%d/%m/%Y')
  end
end

app/controllers/admin/service_desks_controller.rb
class Admin::ServiceDesksController < Admin::AdminController
  def index
    @service_desks = service_desks('all')
    @status = ServiceDesk.status
    @categories = take_categories
  end

  def show
    @service_desk = ServiceDesk.find(params[:id])
    @message = Message.new if @service_desk.in_progress?
    @messages = Message.where(service_desk_id: @service_desk.id) if @service_desk.in_progress?
  end

  def my_service_desks
    @service_desks = service_desks('my')
    @status = ServiceDesk.status
    @categories = take_categories
  end

  def assign_service_desk
    service_desk = ServiceDesk.find(params[:id])
    return redirect_to admin_service_desks_path, alert: 'Não foi possível atribuir chamado' unless service_desk.open?

    service_desk.update(admin_id: current_admin.id)
    service_desk.in_progress!
    redirect_to admin_service_desk_path(service_desk.id), notice: 'Chamado atribuído com sucesso!'
  end

  def close
    service_desk = ServiceDesk.find(params[:id])
    return redirect_to admin_service_desks_path unless service_desk.in_progress?

    service_desk.wait_approval_client!
    flash['notice'] = 'Chamado finalizado com sucesso.'
    redirect_to admin_service_desk_path(service_desk.id)
  end

  private

  def take_categories
    category_all = Category.all
    categories = []
    categories << ['Categoria', nil]
    categories + category_all.map { |category| [category.name, category.id] }
  end

  def service_desks(type)
    @service_desks = ServiceDesk.all if type == 'all'
    @service_desks = ServiceDesk.where(admin_id: current_admin.id) unless type == 'all'
    @service_desks = @service_desks.where(search)
  end

  def search
    query = {}
    search_by_status(query)
    search_by_category(query)
    search_by_order(query)
    query
  end

  def search_by_status(query)
    query[:status] = params[:status] unless params[:status].nil? || params[:status] == ''
  end

  def search_by_category(query)
    query[:category_id] = params[:category_id] unless params[:category_id].nil? || params[:category_id] == ''
  end

  def search_by_order(query)
    query[:order_id] = params[:search].to_i unless params[:search].nil? || params[:search] == ''
  end
end

app/controllers/service_desks_controller.rb
class ServiceDesksController < ApplicationController
  before_action :authenticate_client!
  before_action :set_service_desk, only: %i[show edit update destroy]

  def index
    @service_desks = service_desks
    @status = ServiceDesk.status
    @categories = take_categories
  end

  def show
    @message = Message.new if @service_desk.in_progress?
    @messages = Message.where(service_desk_id: @service_desk.id) unless @service_desk.open?
    return unless @service_desk.client.id != current_client.id

    redirect_to service_desks_path, alert: 'Chamado não encontrado!'
  end

  def new
    @service_desk = ServiceDesk.new
    @categories = Category.all_categories
    @orders_products = take_orders_and_products(current_client.id)
  end

  def create
    service_desk_params = params.require(:service_desk).permit(:client_id, :category_id, :order_id, :product_id,
                                                               :description)
    @service_desk = ServiceDesk.new(service_desk_params)
    return redirect_to service_desk_path(@service_desk.id), notice: 'Chamado aberto com sucesso!' if @service_desk.save

    @categories = Category.all_categories
    @orders_products = take_orders_and_products(current_client.id)
    flash.now['alert'] = 'Não foi possível abrir chamado'
    render 'new'
  end

  def edit
    @categories = Category.all_categories
    @orders_products = take_orders_and_products(current_client.id)
  end

  def update
    service_desk_params = params.require(:service_desk).permit(:client_id, :category_id, :order_id, :product_id,
                                                               :description)
    if @service_desk.update(service_desk_params)
      return redirect_to service_desk_path(@service_desk.id), notice: 'Chamado alterado com sucesso!'
    end

    @categories = Category.all_categories
    @orders_products = take_orders_and_products(current_client.id)
    flash.now['alert'] = 'Não foi possível editar chamado'
    render 'edit'
  end

  def destroy
    return unless @service_desk.open?

    @service_desk.destroy
    redirect_to service_desks_path, notice: 'Chamado excluído com sucesso'
  end

  def change_to_wait_approval_client
    service_desk = ServiceDesk.find(params[:id])
    return redirect_to service_desks_path unless service_desk.in_progress?

    service_desk.wait_approval_client!
    flash['notice'] = 'Chamado finalizado com sucesso. Não se esqueça de responder à pesquisa.'
    redirect_to service_desk_path(service_desk.id)
  end

  def close
    service_desk = ServiceDesk.find(params[:id])
    return redirect_to service_desks_path unless service_desk.wait_approval_client?

    service_desk.update(survey: params[:survey])
    service_desk.closed!
    flash['notice'] = 'Obrigado pela resposta. Qualquer dúvida entre em contato conosco.'
    redirect_to service_desk_path(service_desk.id)
  end

  private

  def set_service_desk
    @service_desk = ServiceDesk.find(params[:id])
  end

  def take_orders_and_products(client_id)
    orders = Order.where(client_id: client_id)
    orders_products = []
    orders_products << ['Selecione o seu Pedido/Produto', nil]
    return orders_products if orders.empty?

    # rubocop:disable Layout/LineLength
    orders_products + orders.map { |order| ["##{order.order_code} - #{order.product.name unless order.product.nil?}", order.id] }
    # rubocop:enable Layout/LineLength
  end

  def take_categories
    category_all = Category.all_categories
    categories = []
    categories << ['Categoria', nil]
    categories + category_all.map { |category| [category.name, category.id] }
  end

  def service_desks
    @service_desks = ServiceDesk.where(client_id: current_client.id)
    @service_desks = @service_desks.where(search)
  end

  def search
    query = {}
    search_by_status(query)
    search_by_category(query)
    search_by_order(query)
    query
  end

  def search_by_status(query)
    query[:status] = params[:status] unless params[:status].nil? || params[:status] == ''
  end

  def search_by_category(query)
    query[:category_id] = params[:category_id] unless params[:category_id].nil? || params[:category_id] == ''
  end

  def search_by_order(query)
    query[:order_id] = params[:search].to_i unless params[:search].nil? || params[:search] == ''
  end
end

app/views/service_desks/_form.html.erb
<% if @service_desk.errors.any? %>
  <span>Verifique os campos abaixo:</span>
  <ul>
    <% @service_desk.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @service_desk, html: {class: 'ls-form'}) do |f| %>
  <fieldset>
    <label class="ls-label col-md-4">
      <h3>Solicitante: <%= current_client.name %></h4><br>
      <h5>E-mail: <%= current_client.email %></h4><br>
      <%= f.hidden_field :client_id, value: "#{current_client.id}" %>
    </label>
  </fieldset>
  <fieldset class="ls-form-horizontal">
    <label class="ls-label col-md-4 col-xs-12">
      <%= f.label :category_id, 'Categoria', class: 'ls-label-text' %>
      <div class="ls-custom-select">
        <%= f.collection_select(:category_id, @categories, :id, :name, {}, class:'ls-custom')%>
      </div>
    </label>
    <label class="ls-label col-md-4 col-xs-12">
      <%= f.label :order_id, 'Pedido/Produto', class: 'ls-label-text' %>
      <div class="ls-custom-select">
        <%= f.select(:order_id, options_for_select(@orders_products, 'selecione'), {}, class:'ls-custom') %>
      </div>
    </label>
    <label class="ls-label col-md-12">
      <%= f.label :description, 'Descrição', class: 'ls-label-text' %>
      <%= f.text_area :description, cols: 20, rows: 8 %>
    </label>
    <div class="ls-actions-btn">
      <%= f.submit 'Enviar', class: 'ls-btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/service_desks/_list_service_desks.html.erb
<table id="service-desks" class="ls-table ls-txt-center ls-table-striped ls-bg-header">
  <thead>
    <th>#</th>
    <th>Categoria</th>
    <th>Solicitante</th>
    <th>Data de Abertura</th>
    <th>Data de Fechamento</th>
    <th>Atendente</th>
    <th>Status</th>
    <th colspan='3'>Ações</th>
  </thead>
  <tbody>
    <% @service_desks.each do |service_desk| %>
      <tr id="service-desk-<%= service_desk.id %>">
        <td><%= service_desk.id %></td>
        <td><%= service_desk.category.name %></td>
        <td><%= service_desk.client.name %></td>
        <td><%= service_desk.created %></td>
        <td><%= service_desk.closed if service_desk.closed? %></td>
        <td><%= service_desk.admin.name unless service_desk.admin.nil? %></td>
        <td><%= ServiceDesk.human_enum_name(:status, service_desk.status) %></td>
        <% if service_desk.open? %>
          <td><%= link_to 'Detalhes', service_desk_path(service_desk.id), {class: 'ls-btn ls-btn-primary', name: 'detalhes'} %></td>
          <td><%= link_to 'Editar', edit_service_desk_path(service_desk.id), {class: 'ls-btn ls-btn', name: 'editar'} %></td>
          <td><%= link_to 'Deletar', service_desk_path(service_desk.id), {class: 'ls-btn ls-btn-primary-danger', id: 'deletar', name: 'deletar', method: :delete, data: { confirm: 'Você está certo disso?' }} %></td>
        <% else %>
          <% if service_desk.in_progress? %>
            <td><%= link_to 'Detalhes', service_desk_path(service_desk.id), {class: 'ls-btn ls-btn-primary', name: 'detalhes'} %></td>
            <td colspan='2'>
              <%= button_to "Finalizar Chamado", change_to_wait_approval_client_service_desk_path(service_desk.id),
              data: { confirm: "O chamado não poderá ser reaberto após finalização, confirmar?" },
              method: :post, class: 'ls-btn ls-btn-danger' %>
            </td>
          <% else %>
            <td colspan='3'><%= link_to 'Detalhes', service_desk_path(service_desk.id), {class: 'ls-btn ls-btn-primary', name: 'detalhes'} %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %> 
  </tbody>
</table>

app/views/service_desks/_messages.html.erb
<div class="container-fluid" id="messages" style="overflow-y: scroll; height: 200px;">
  <% unless @messages.empty? %>
    <% @messages.each do |message| %>
      <% unless message.admin.nil? %>
        <div class="row">
          <div class="format-message-receive ls-word-break ls-txt-left">
            <p><%= message.content %></p>
            <p><b>Atendente: <%= message.admin.name %></b></p>
            <p>Enviado em: <%= message.created %></p>
          </div>
        </div>
      <% else %>
        <div class="row wrap">
          <div class='ls-float-right format-message-send ls-display-inline-block ls-word-break ls-txt-right'>          
            <p><%= message.content %></p>
            <p><b>Cliente: <%= message.client.name %></b></p>
            <p>Enviado em: <%= message.created %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>
<br>
<% if @service_desk.in_progress? %>
  <div class="row">
    <div class="col-md-12">
      <%= form_with(model: @message, html: {class: 'ls-form col-md-12 ls-form-inline'}) do |f| %>
        <%= f.hidden_field :service_desk_id, value: "#{@service_desk.id}" %>
        <%= f.hidden_field :client_id, value: "#{current_client.id}" %>
        <fieldset>
          <label class="ls-label col-md-11 col-xs-12">
            <%= f.label :content, 'Mensagem:', class: 'ls-label-text' %>
            <%= f.text_field :content %>
          </label>
          <div class="col-md-1">
            <%= f.submit 'Enviar', class: 'ls-btn-primary' %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
<% end %>

app/views/service_desks/edit.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-panel-pabx">Chamados</h1>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3 ls-ico-plus">Edição de Chamado</h2>
    </header>
    <%= render 'form', service_desk: @service_desk %>
  </div>
</div>

app/views/service_desks/index.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-panel-pabx">Chamados
    <div class='col-md-offset-4 ls-float-right'>
      <%= link_to 'Abrir Chamado', new_service_desk_path, class: 'ls-btn ls-btn-primary' if client_signed_in? %>
    </div>
  </h1>
  <% unless @service_desks.nil? %>
    <div class="ls-box-filter">  
      <%= form_with(url: service_desks_path, method: :get, html: {class: 'ls-form ls-form-inline'}) do |f| %>
        <fieldset>
          <label class="ls-label col-md-4 col-xs-12">
            <b class='ls-label-text'>Busca</b>
            <div class="ls-custom-select">
              <%= f.select :status, options_for_select(@status), {name: 'status', class: 'ls-select'} %>
            </div>
          </label>
          <label class="ls-label col-md-4 col-xs-12">
            <div class="ls-custom-select">
              <%= f.select :category_id, options_for_select(@categories), {name: 'category', class: 'ls-select'} %>
            </div>
          </label>
          <label class="ls-label col-md-3 col-xs-12">
            <%= f.text_field :search, class: 'ls-field' %>
          </label>
          <label class="ls-label col-md-1 col-xs-12">
            <%= f.submit 'Filtrar', class: 'ls-btn' %>
          </label>
        </fieldset>
      <% end %>
    </div>
    <% if @service_desks.empty? %>
      <p class='alert'><strong>Não há chamados a serem exibidos</strong></p>
    <% else %>
      <%= render 'list_service_desks', service_desks: @service_desks %>
    <% end %>
  <% end %>
</div>

app/views/service_desks/new.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-panel-pabx">Chamados</h1>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3 ls-ico-plus">Abertura de Chamado</h2>
    </header>
    <%= render 'form', service_desk: @service_desk %>
  </div>
</div>

app/views/service_desks/show.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-panel-pabx">Dados do Chamado</h1>
  <% if @service_desk.wait_approval_client? %>
    <div class='ls-box ls-board-box'>
      <header class='ls-info-header'>
        <div class='col-md-6'>
          <h2 class='ls-title-3 ls-ico-pencil'>Pesquisa de Satisfação</h2>
        </div>
      </header>
      <div class="col-md-12">
          <%= form_with(url: close_service_desk_path(@service_desk.id), method: :post, html: {class: 'ls-form ls-form-horizontal row'}) do |f| %>
            <fieldset>
              <label class="col-md-12">
                <h3>Seu problema foi resolvido?</h3><br>
              </label>
              <label class="col-md-1 col-md-xs-12 ls-label-text">
                <%= f.radio_button :survey, 1, {id: 'survey_yes', class: 'ls-field-radio'} %>
                <%= f.label :survey_yes, 'Sim' %>
              </label>
              <label class="col-md-2 ls-label-text">
                <%= f.radio_button :survey, 0, {id: 'survey_no', class: 'ls-field-radio'} %>
                <%= f.label :survey_no, 'Não' %>
              </label>
            </fieldset>
            <div class="ls-actions-btn">
              <%= f.submit 'Enviar', class: 'ls-btn ls-btn-dark' %>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>
  <div class='ls-box ls-board-box'>
    <header class='ls-info-header'>
      <div class='col-md-6'>
        <h2 class='ls-title-3 ls-ico-eye'>#<%= @service_desk.id %></h2>
      </div>
      <div class='col-md-offset-4 ls-float-right'>
        <% if @service_desk.open? %>
          <%= link_to 'Editar', edit_service_desk_path(@service_desk.id), {class: 'ls-btn ls-btn', name: 'editar'} %>
          <%= link_to 'Deletar', service_desk_path(@service_desk.id), {class: 'ls-btn ls-btn-primary-danger', id: 'deletar', name: 'deletar', method: :delete, data: { confirm: 'Você está certo disso?' }} %>
        <% end %>
        <% if @service_desk.in_progress? %>
          <%= button_to "Finalizar Chamado", change_to_wait_approval_client_service_desk_path(@service_desk.id),
          data: { confirm: "O chamado não poderá ser reaberto após finalização, confirmar?" },
          method: :post, class: 'ls-btn ls-btn-danger' %>
        <% end %>
      </div>
    </header>
    <table class='ls-table'>
      <tbody>
        <tr>
          <td><strong>Solicitante: </strong><%= @service_desk.client.name %></td>
          <td><strong>E-mail: </strong><%= @service_desk.client.email %></td>
        </tr>
        <% unless @service_desk.admin.nil? %>
          <tr>
            <td><strong>Atendente: </strong><%= @service_desk.admin.name %></td>
            <td><strong>E-mail: </strong><%= @service_desk.admin.email %></td>
          </tr>
        <% end %>
        <tr>
          <td><strong>Data de Abertura: </strong><%= @service_desk.created %></td>
          <% if @service_desk.closed? %>
            <td><strong>Data de Fechamento: </strong><%= @service_desk.closed %></td>
          <% end %>
        </tr>
        <tr>
          <td><strong>Status: </strong><%= ServiceDesk.human_enum_name(:status, @service_desk.status) %></td>
        </tr>
        <tr>
          <td><strong>Categoria: </strong><%= @service_desk.category.name %></td>
        </tr>
        <% unless @service_desk.order.nil? %>
          <tr>
            <td><strong>Pedido: </strong><%= @service_desk.order.order_code unless @service_desk.order.nil? %></td>
            <td><strong>Produto: </strong><%= @service_desk.order.product.name unless @service_desk.order.product.nil? %></td>
          </tr>
        <% end %>
        <tr>
          <td>
            <strong>Descrição: </strong><br><br>
            <%= @service_desk.description %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <% unless @service_desk.open? %>
    <div class='ls-box ls-board-box'>
      <header class='ls-info-header'>
          <h2 class='ls-title-4 ls-ico-mobile ls-sm-margin-top'>Chat</h2>
      </header>
      <%= render 'messages', message: @message %>
    </div>
  <% end %>
</div>