config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/home/profile', to: 'home#profile'
  devise_for :admins, path: 'admins'
  devise_for :clients, path: 'clients'
  get '/clients/delete', to: 'clients#delete'
  post '/clients/delete', to: 'clients#delete'
  get '/clients/changeaccount', to: 'clients#changeaccount'
  post '/clients/changeaccount', to: 'clients#changeaccount'
  get 'search', to: 'admin/clients#search'

  resources :messages, only: %i[create]

  resources :orders, only: %I[index show] do
    post 'cancel', on: :member
    post 'pay', on: :member
  end

  resources :service_desks do
    post 'change_to_wait_approval_client', on: :member
    post 'close', on: :member
  end

  resources :credit_cards, only: %I[index new create] do
    post :down, :up, on: :member
  end

  resources :products, only: %I[index show] do
    post 'cancel', on: :member
    get 'buy', on: :member
    get 'choose_period', on: :member
    post 'create_order', on: :member
  end

  namespace :admin do
    resources :categories, only: %i[index new create edit update destroy]
    resources :clients, only: %I[index show]
    resources :products, only: %I[index show] do
      post 'cancel', on: :member
    end
    resources :orders, only: %I[index show] do
      post 'cancel', on: :member
    end
    resources :service_desks, only: %I[index show] do
      post 'close', on: :member
    end

    get 'my_service_desks', to: 'service_desks#my_service_desks'
    post 'assign_service_desk/:id', to: 'service_desks#assign_service_desk', as: :assign_service_desk
    resources :messages, only: %i[create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :orders, only: :show do
        patch 'payment', on: :collection
      end
      patch 'cancelation/:id', to: 'orders#cancelation', as: 'cancelation'
      get 'card_banners/:token', to: 'banners#show'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :client
  belongs_to :order

  enum status: { waiting_payment: 0, paid: 1, installing: 2, installed: 3, canceled: 4 }

  def install
    return unless paid? || installing?

    resp = Faraday.post("#{ApisDomains.products}/api/v1/customer_product/installations", install_params,
                        'Content-Type' => 'application/json')
    if resp.status == 201
      self.server = JSON.parse(resp.body)['server_code']
      installed!
      order.completed!
    else
      installing!
    end
  end

  def cancel
    return unless installed?

    resp = Faraday.patch("#{ApisDomains.products}/api/v1/customer_product/installations/#{code}/inactive")
    return false unless resp.status == 201

    canceled!
    true
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase if code.nil?
    code
  end

  def owner?(client)
    self.client == client
  end

  def self.send_order(params, value, period)
    request = JSON.generate(client_eni: params['client_eni'], plan_id: params['plan_id'],
                            period: period, value: value)

    headers = { 'Content-Type' => 'application/json' }
    response = Faraday.post("#{ApisDomains.sales}/api/v1/orders", request, headers)
    return nil if response.status == 500

    result = JSON.parse(response.body)
    return result unless response.status == 201

    Product.build_order(result)
  end

  def self.generate(order)
    resp = Faraday.get("#{ApisDomains.products}/api/v1/plans/#{order.plan_id}")
    return unless resp.status == 200

    plan_data = JSON.parse(resp.body)
    name = plan_data['product_group']['name']
    group = plan_data['product_group']['key']
    plan = plan_data['name']

    Product.create!(name: name, plan: plan, group: group, client: order.client,
                    frequency: order.frequency, price: order.price, order: order)
  end

  def self.build_order(result)
    client = Client.find_by(eni: result['client_eni'])
    order = Order.create(order_code: result['id'], client: client, frequency: result['period'],
                         price: result['value'], plan_id: result['plan_id'])
    order.save_order
  end

  def self.find_group_id(key)
    resp = Faraday.get("#{ApisDomains.products}/api/v1/product_groups")
    return unless resp.status == 200

    groups = JSON.parse(resp.body)
    groups.each do |g|
      return g['id'] if g['key'] == key
    end
  end

  private

  def install_params
    JSON.generate({ customer: client.eni, product_code: generate_code, plan_id: order.plan_id })
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  def index
    begin
      clients = Client.all
      raise 'Nenhum cliente' unless clients.any?

      clients.each do |client|
        Order.pull_orders(client.eni)
      end
    rescue StandardError
      flash.now[:alert] = 'Falha ao atualizar pedidos! Se algum pedido não aparecer, tente novamente mais tarde'
    end
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def cancel
    product = Product.find(params[:id])
    if product.cancel
      redirect_to admin_product_path(product.id), notice: 'Produto cancelado com sucesso'
    else
      redirect_to admin_product_path(product.id), alert: 'Falha ao cancelar o produto, tente novamente mais tarde!'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_client!

  def index
    @products = current_client.products
    products_instal(@product)
    @active_products = current_client.products.installed + current_client.products.installing
    @cancelled_products = current_client.products.canceled
  end

  def show
    @product = Product.find(params[:id])
    @product.install if @product.installing? && check_products_status

    return if @product.owner?(current_client)

    redirect_to root_path, alert: 'Você não tem autorização para acessar esta página'
  end

  def cancel
    product = Product.find(params[:id])
    if product.owner?(current_client)
      if product.cancel
        redirect_to product, notice: 'Produto cancelado com sucesso'
      else
        redirect_to product, alert: 'Falha ao cancelar o produto, tente novamente mais tarde!'
      end
    else
      redirect_to root_path, alert: 'Você não tem autorização para isso'
    end
  end

  def buy
    @product = Product.find(params['id'])
    @client = current_client
    @plans = Plan.group_search(@product.group)
  end

  def choose_period
    @product = Product.find(params['id'])
    @client = current_client
    @plan = Plan.find(params['plan'].to_i)
    @prices = Price.all(params['plan'])
  end

  def create_order
    price = Price.find(params[:price], params[:plan_id])
    order_params = params.permit(:client_eni, :plan_id)
    order = Product.send_order(order_params, price[0].value, price[0].period)
    redirect_order(order)
  end

  private

  def redirect_order(order)
    if order.nil? || order.is_a?(Array)
      redirect_to product_path(params['id']), alert: 'Falha ao criar pedido, tente novamente mais tarde!'
    else
      redirect_to orders_path, notice: 'Pedido criado com sucesso'
    end
  end

  def products_instal(products)
    products&.each { |prod| prod.install if prod.paid? && check_products_status }
  end
end

app/views/products/buy.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-table-alt">Produtos</h1>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3 ls-ico-plus">Comprar Novamente</h2>
    </header>
    <%= form_with(url: choose_period_product_path, method: :get, class: "ls-form", html: { 'data-ls-module': "form" }) do |f|%>
      <%= f.hidden_field :client_eni, value: current_client.eni %>
      <fieldset>
        <label class="ls-label col-md-4">
          <%= f.label :name, 'Produto', class:"ls-label-text"%><br/>
          <%= f.text_field(:name, value: @product.name, disabled: true) %>
        </label>
      </fieldset>
      <fieldset>
        <label class="ls-label col-md-4">
          <%= f.label :plan, 'Plano', class:"ls-label-text" %> <br/>
          <div class="ls-custom-select">
            <%= f.collection_select(:plan, @plans, :id, :name, { include_blank: 'Selecione o plano' } ) %>
          </div>
        </label>
        <div class="ls-actions-btn">
          <%= f.submit 'Escolher Periodicidade', class:'ls-btn-primary' %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/products/choose_period.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-table-alt">Produtos</h1>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3 ls-ico-plus">Comprar Novamente</h2>
    </header>
    <%= form_with(url: create_order_product_path, method: :post, class: "ls-form", html: { 'data-ls-module': "form" }) do |f|%>
      <%= f.hidden_field :client_eni, value: current_client.eni %>
      <%= f.hidden_field :plan_id, value: @plan.id %>
      <fieldset>
        <div class="ls-label col-md-4">
          <%= f.label :name, 'Produto', class:"ls-label-text"%><br/>
          <%= f.text_field(:name, value: @product.name, disabled: true) %>
        </div>
      </fieldset>

      <fieldset>
        <div class="ls-label col-md-4">
          <%= f.label :plan, 'Plano', class:"ls-label-text"%><br/>
          <%= f.text_field(:name, value: @plan.name, disabled: true) %>
        </div>
      </fieldset>

      <fieldset>
        <div class="ls-label col-md-4">
          <%= f.label :price, 'Periodicidade', class:"ls-label-text" %> <br/>
          <div class="ls-custom-select">
            <%= f.collection_select(:price, @prices, :id, :period_with_price, { include_blank: 'Selecione a periodicidade' } ) %>
          </div>
        </div>
        <div class="ls-actions-btn">
          <%= f.submit 'Criar Pedido', class:'ls-btn-primary' %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  <h1 class="ls-no-margin-left ls-no-margin-right ls-title-intro ls-ico-table-alt">Produtos</h1>
  <% if @products.any? %>
    <% if @active_products.any? %>
      <div class="ls-box ls-board-box">
        <header class="ls-info-header">
          <h2 class="ls-title-3">Produtos Ativos</h2>
        </header>
        <table id="actives" class="ls-table ls-txt-center ls-table-striped ls-bg-header">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Plano</th>
              <th>Status</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            <% @active_products.each do |product| %>
              <tr id=<%= product.id %>>
                <td><%= product.name %></td>
                <td><%= product.plan %></td>
                <td><%= Product.human_enum_name(:status, product.status) %></td>
                <td><%= link_to 'Detalhes', product, class: 'ls-btn ls-btn-primary' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
    <% if @cancelled_products.any? %>
      <div class="ls-box ls-board-box">
        <header class="ls-info-header">
          <h2 class="ls-title-3">Produtos Cancelados</h2>
        </header>
        <table id="cancelled" class="ls-table ls-txt-center ls-table-striped ls-bg-header">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Plano</th>
              <th>Status</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            <% @cancelled_products.each do |product| %>
              <tr id=<%= product.id %>>
                <td><%= product.name %></td>
                <td><%= product.plan %></td>
                <td><%= Product.human_enum_name(:status, product.status) %></td>
                <td><%= link_to 'Detalhes', product, class: 'ls-btn ls-btn-primary' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  <% else %>
    <h3>Você não possui nenhum produto</h3>
    <p>Clique <%= link_to 'AQUI', orders_path %> para visualizar seus pedidos pendentes</p>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container-fluid">

  <div class="details">
    <div class="ls-list">
      <header class="ls-list-header">
        <div class="ls-list-title col-md-9">
          <a><h1><%= @product.name %></h1></a>
        </div>
      </header>
      
      <div class="ls-list-content ">
        <div class="col-xs-12 col-md-6">
          <span class="ls-list-label">Status</span>
          <strong><%= Product.human_enum_name(:status, @product.status) %></strong>
        </div>
        <div class="col-xs-12 col-md-6">
          <span class="ls-list-label">Servidor de instalação</span>
          <strong><%= @product.server ? @product.server : 'Aguardando' %></strong>
        </div>
      </div>

      <div class="ls-list-content ">
        <div class="col-xs-12 col-md-6">
          <span class="ls-list-label">Grupo</span>
          <strong><%= @product.group %></strong>
        </div>
        <div class="col-xs-12 col-md-6">
          <span class="ls-list-label">Plano</span>
          <strong><%= @product.plan %></strong>
        </div>
      </div>

      <div class="ls-list-description ls-list-content">
        <div class="col-xs-12 col-md-6">
          <span class="ls-list-label">Periodicidade</span>
          <strong><%= @product.frequency %></strong>
        </div>
        <div class="col-xs-12 col-md-6">
          <span class="ls-list-label">Preço</span>
          <strong><%= number_to_currency(@product.price) %></strong>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Comprar Novamente', buy_product_path(@product), class: 'ls-btn-primary ls-btn' %>
  <% unless @product.canceled? %>
    <%= link_to 'Cancelar produto', cancel_product_path(@product),
                                    data: { confirm: "O produto e/ou o plano podem não estar mais disponiveis no futuro, confirmar?" },
                                    method: :post, class: 'ls-btn-primary-danger ls-btn' %>
  <% end %>
</div>